### ISSUE TITLE
Index Error on MacOS

### ISSUE THREAD

**Issue by vnktsh** [MohamedAliRashad/flask-ngrok2#5]
Index error on MacOS Ventura
```
 * Serving Flask app 'app'
 * Debug mode: off
2023-03-13 20:12:47,277 - werkzeug - INFO - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
2023-03-13 20:12:47,278 - werkzeug - INFO - Press CTRL+C to quit
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test/lib/python3.10/threading.py", line 1378, in run
    self.function(*self.args, **self.kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test/lib/python3.10/site-packages/flask_ngrok2.py", line 92, in start_ngrok
    ngrok_address = _run_ngrok(port, auth_token)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test/lib/python3.10/site-packages/flask_ngrok2.py", line 60, in _run_ngrok
    tunnel_url = j["tunnels"][0]["public_url"]  # Do the parsing of the get
IndexError: list index out of range

```

**Comment by malufett** [comment]
up I got the same error
